meta:
  name: "polymarket_comprehensive_scraper"
  description: "Comprehensive Polymarket API scraper for prediction market data and arbitrage detection"
  start_url: "https://gamma-api.polymarket.com/markets"
  allowed_domains:
    - "gamma-api.polymarket.com"
    - "clob.polymarket.com"

fetcher:
  type: "api"
  method: "GET"
  timeout_ms: 30000
  headers:
    Accept: "application/json"
    Content-Type: "application/json"
    User-Agent: "Polymarket-Arbitrage-Bot/1.0"

database:
  url: "postgresql://postgres:1qazZAQ!@localhost:5432/arbitrage_bot_db"
  bookmaker_name: "Polymarket"
  category_name: "Prediction Markets"

instructions:
  - type: "collect"
    name: "gamma_markets"
    container_selector: "$"
    item_selector: "$[*]"
    limit: 100
    fields:
      market_id:
        selector: "$.id"
        attribute: "text"
        required: true
        processors: ["trim"]

      slug:
        selector: "$.slug"
        attribute: "text"
        processors: ["trim"]

      question:
        selector: "$.question"
        attribute: "text"
        processors: ["trim", "clean_text"]

      active:
        selector: "$.active"
        attribute: "text"
        processors: ["trim"]

      volume:
        selector: "$.volume"
        attribute: "text"
        processors: ["number"]
        default: "0"

      liquidity:
        selector: "$.liquidity"
        attribute: "text"
        processors: ["number"]
        default: "0"

      outcome_prices:
        selector: "$.outcomePrices"
        attribute: "text"
        processors: ["trim"]

      outcomes:
        selector: "$.outcomes"
        attribute: "text"
        processors: ["trim"]

      start_date:
        selector: "$.startDate"
        attribute: "text"
        processors: ["date"]

      end_date:
        selector: "$.endDate"
        attribute: "text"
        processors: ["date"]

      description:
        selector: "$.description"
        attribute: "text"
        processors: ["trim", "clean_text"]

      enable_order_book:
        selector: "$.enableOrderBook"
        attribute: "text"
        processors: ["trim"]

      market_type:
        selector: "$.marketType"
        attribute: "text"
        processors: ["trim"]
        default: "binary"