meta:
  name: "polymarket_comprehensive_scraper"
  description: "Comprehensive Polymarket API scraper for prediction market data and arbitrage detection"
  start_url: "https://clob.polymarket.com/markets"
  allowed_domains:
    - "gamma-api.polymarket.com"
    - "clob.polymarket.com"

fetcher:
  type: "api"
  method: "GET"
  timeout_ms: 30000
  headers:
    Accept: "application/json"
    Content-Type: "application/json"
    User-Agent: "Polymarket-Arbitrage-Bot/1.0"

database:
  bookmaker_name: "Polymarket"
  category_name: "Prediction Markets"

instructions:
  - type: "collect"
    name: "gamma_markets"
    container_selector: "$"
    item_selector: "$[*]"
    limit: 50
    fields:
      market_id:
        selector: "$.id"
        attribute: "text"
        required: true
        processors: ["trim"]

      slug:
        selector: "$.slug"
        attribute: "text"
        processors: ["trim"]

      question:
        selector: "$.question"
        attribute: "text"
        processors: ["trim", "clean_text"]

      active:
        selector: "$.active"
        attribute: "text"
        processors: ["trim"]

      volume:
        selector: "$.volume"
        attribute: "text"
        processors: ["number"]
        default: "0"

      liquidity:
        selector: "$.liquidity"
        attribute: "text"
        processors: ["number"]
        default: "0"

      outcome_prices:
        selector: "$.outcomePrices"
        attribute: "text"
        processors: ["trim"]

      # Individual outcome prices for easier processing
      price_yes:
        selector: "$.outcomePrices"
        attribute: "text"
        processors:
          - name: "outcome_price_extractor"
            args:
              index: 0
        default: "0.5"

      price_no:
        selector: "$.outcomePrices"
        attribute: "text"
        processors:
          - name: "outcome_price_extractor"
            args:
              index: 1
        default: "0.5"

      outcomes:
        selector: "$.outcomes"
        attribute: "text"
        processors: ["trim"]

      start_date:
        selector: "$.startDate"
        attribute: "text"
        processors:
          - name: "date"
            args:
              output_format: "%Y-%m-%d %H:%M:%S"

      end_date:
        selector: "$.endDate"
        attribute: "text"
        processors:
          - name: "date"
            args:
              output_format: "%Y-%m-%d %H:%M:%S"

      description:
        selector: "$.description"
        attribute: "text"
        processors: ["trim", "clean_text"]

      market_type:
        selector: "$.marketType"
        attribute: "text"
        processors: ["trim"]
        default: "binary"

      # Additional metadata
      enable_order_book:
        selector: "$.enableOrderBook"
        attribute: "text"
        processors: ["trim"]
        default: "false"